spring:
  jackson:
    default-property-inclusion: NON_NULL
#disabled job run at startup
  batch:
    job:
      enabled: true

# Enable Logging mongo queries

employee:
  excel:
    processingfolder: data/processing/
    resultsfolder: data/results/
search:
  folder: C:\\files\\
  pattern: trade*.json
